export { FaChrome, FaFirefox, FaGithub, IoChatboxSharp, RiCloseLine } from './other'
export {
  TbAdjustmentsHorizontal,
  TbArchive,
  TbBrandGithub,
  TbCheck,
  TbClock,
  TbCoin,
  TbCrown,
  TbDeviceDesktop,
  TbDownload,
  TbEye,
  TbGripVertical,
  TbHeart,
  TbHeartDollar,
  TbLanguage,
  TbLayoutGrid,
  TbLink,
  TbMessageCircle,
  TbMoon,
  TbPaint,
  TbPalette,
  TbPlus,
  TbReset,
  TbSettings2,
  TbSpacingHorizontal,
  TbSparkles,
  TbSun,
  TbSunMoon,
  TbTextSize,
  TbTrash,
  TbTypography,
  TbUpload,
  TbUser,
  TbUserCircle,
} from './tabler'
export type { IconProps, IconType } from './types'
