export { FaChrome, FaFirefox, FaGithub, IoChatboxSharp, RiCloseLine } from './other'
export {
  TbAdjustmentsHorizontal,
  TbArchive,
  TbBlur,
  TbCheck,
  TbClock,
  TbCrown,
  TbDownload,
  TbGripVertical,
  TbHeartDollar,
  TbLanguage,
  TbLayoutGrid,
  TbLink,
  TbMessageCircle,
  TbPaint,
  TbPalette,
  TbPlus,
  TbSettings2,
  TbSpacingHorizontal,
  TbSparkles,
  TbSunMoon,
  TbTextSize,
  TbTrash,
  TbTypography,
  TbUpload,
  TbUser,
  TbUserCircle,
} from './tabler'
export type { IconProps, IconType } from './types'
