/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const button: string;
const icon: string;

export {
	button,
	icon
};

export default {
	button,
	icon
}
