export const RUNTIME_FAILURE_CODES = [
  'PLAYER_TARGET_MISSING',
  'CONTROL_TARGET_MISSING',
  'CHAT_SOURCE_PENDING',
  'CHAT_SOURCE_UNAVAILABLE',
  'BORROWED_IFRAME_DETACHED',
  'IFRAME_DOCUMENT_NOT_READY',
  'RESTORE_TARGET_MISSING',
  'PRESENTATION_TARGET_REPLACED',
  'RETRY_EXHAUSTED',
] as const

export type RuntimeFailureCode = (typeof RUNTIME_FAILURE_CODES)[number]
