/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const sliderWrapper: string;
const sliderTrack: string;
const sliderThumb: string;

export {

};

export default {
	"slider-wrapper": sliderWrapper,
	"slider-track": sliderTrack,
	"slider-thumb": sliderThumb
}
