/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const wrapper: string;
const input: string;
const label: string;

export {
	wrapper,
	input,
	label
};

export default {
	wrapper,
	input,
	label
}
