export const CLIP_GEOMETRY_DURATION_MS = 220
export const CLIP_GEOMETRY_EASING = 'cubic-bezier(0.22, 1, 0.36, 1)'
export const CLIP_GEOMETRY_TRANSITION = `${CLIP_GEOMETRY_DURATION_MS}ms ${CLIP_GEOMETRY_EASING}`
