/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const enter: string;
const enterActive: string;
const exit: string;
const exitActive: string;

export {
	enter,
	enterActive,
	exit,
	exitActive
};

export default {
	enter,
	enterActive,
	exit,
	exitActive
}
