/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const RestrictWindow: string;

export {
	RestrictWindow
};

export default {
	RestrictWindow
}
