/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const Resizable: string;
const Container: string;
const dragButton: string;
const dragging: string;
const settingButton: string;
const children: string;
const overlay: string;

export {
	Resizable,
	Container,
	dragButton,
	dragging,
	settingButton,
	children,
	overlay
};

export default {
	Resizable,
	Container,
	dragButton,
	dragging,
	settingButton,
	children,
	overlay
}
