/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const colorPickerWrapper: string;
const colorDisplay: string;
const colorPreviewBackground: string;
const colorPreview: string;
const colorPicker: string;

export {

};

export default {
	"color-picker-wrapper": colorPickerWrapper,
	"color-display": colorDisplay,
	"color-preview-background": colorPreviewBackground,
	"color-preview": colorPreview,
	"color-picker": colorPicker
}
