export const IFRAME_STYLE_MARKER_ATTR = 'data-ylc-style-injected'
export const IFRAME_CHAT_BODY_CLASS = 'custom-yt-app-live-chat-extension'
export const IFRAME_CHAT_ONLY_CLASS = 'chat-only-display'
export const IFRAME_CHAT_ONLY_TRANSITION_CLASS = 'chat-only-transition-ready'
export const IFRAME_CHAT_ONLY_MEASURING_CLASS = 'chat-only-measuring'
export const IFRAME_CHAT_ONLY_TARGET_HEIGHT_VAR = '--extension-chat-only-target-height'
