export type Styles = {
  'author-name': string;
  'author-photo': string;
  chat: string;
  'clip-path-enable': string;
  contents: string;
  custom: string;
  'custom-yt-app-live-chat-extension': string;
  emoji: string;
  icon: string;
  input: string;
  'item-scroller': string;
  items: string;
  label: string;
  'label-icon': string;
  'left-arrow-container': string;
  member: string;
  menu: string;
  message: string;
  'panel-pages': string;
  'picker-buttons': string;
  right: string;
  'right-arrow-container': string;
  separator: string;
  timestamp: string;
  title: string;
  tooltip: string;
  'yt-dropdown-menu': string;
  'yt-emoji-picker-category-renderer': string;
  'yt-img-shadow': string;
  'yt-live-chat-author-chip': string;
  'yt-live-chat-banner-renderer': string;
  'yt-live-chat-icon-toggle-button-renderer': string;
  'yt-live-chat-item-list-renderer': string;
  'yt-live-chat-message-input-renderer': string;
  'yt-live-chat-renderer': string;
  'yt-live-chat-restricted-participation-renderer': string;
  'yt-live-chat-text-input-field-renderer': string;
  'yt-live-chat-text-message-renderer': string;
  'yt-live-chat-ticker-renderer': string;
  'yt-live-chat-viewer-engagement-message-renderer': string;
  'yt-spec-button-shape-next--mono': string;
  'yt-spec-button-shape-next--text': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
