/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const loader: string;
const l13: string;

export {
	loader,
	l13
};

export default {
	loader,
	l13
}
