/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const sliderWrapper: string;
const sliderTrack: string;
const sliderThumb: string;

export {
	sliderWrapper as "slider-wrapper",
	sliderTrack as "slider-track",
	sliderThumb as "slider-thumb"
};

export default {
	"slider-wrapper": sliderWrapper,
	"slider-track": sliderTrack,
	"slider-thumb": sliderThumb
}
