/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const settings: string;
const content: string;
const contentItem: string;
const disable: string;
const title: string;
const titleWithIcon: string;
const footer: string;
const help: string;

export {
	settings,
	content,
	disable,
	title,
	footer,
	help
};

export default {
	settings,
	content,
	"content-item": contentItem,
	disable,
	title,
	"title-with-icon": titleWithIcon,
	footer,
	help
}
