/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const Modal: string;
const Overlay: string;
const content: string;
const actions: string;
const buttonDelete: string;
const buttonCancel: string;

export {
	Modal,
	Overlay,
	content,
	actions,
	buttonDelete,
	buttonCancel
};

export default {
	Modal,
	Overlay,
	content,
	actions,
	buttonDelete,
	buttonCancel
}
