/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const contentPresetContainer: string;
const presetItem: string;
const dragging: string;
const flex: string;
const leftContainer: string;
const dragIcon: string;
const title: string;
const rightContainer: string;
const applyStyleButton: string;
const deleteButton: string;
const addPresetItem: string;
const disable: string;

export {
	contentPresetContainer as "content-preset-container",
	presetItem as "preset-item",
	dragging,
	flex,
	leftContainer,
	dragIcon,
	title,
	rightContainer,
	applyStyleButton,
	deleteButton,
	addPresetItem as "add-preset-item",
	disable
};

export default {
	"content-preset-container": contentPresetContainer,
	"preset-item": presetItem,
	dragging,
	flex,
	leftContainer,
	dragIcon,
	title,
	rightContainer,
	applyStyleButton,
	deleteButton,
	"add-preset-item": addPresetItem,
	disable
}
