/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const contentSettingContainer: string;
const contentSettingItem: string;
const disable: string;
const titleWithIcon: string;
const preset: string;
const open: string;
const title: string;
const data: string;

export {
	contentSettingContainer as "content-setting-container",
	contentSettingItem as "content-setting-item",
	disable,
	titleWithIcon as "title-with-icon",
	preset,
	open,
	title,
	data
};

export default {
	"content-setting-container": contentSettingContainer,
	"content-setting-item": contentSettingItem,
	disable,
	"title-with-icon": titleWithIcon,
	preset,
	open,
	title,
	data
}
