/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const settings: string;
const header: string;
const menu: string;
const menuItem: string;
const selectedMenuItem: string;
const closeButton: string;
const content: string;
const footer: string;
const help: string;

export {
	settings,
	header,
	menu,
	menuItem as "menu-item",
	selectedMenuItem as "selected-menu-item",
	closeButton as "close-button",
	content,
	footer,
	help
};

export default {
	settings,
	header,
	menu,
	"menu-item": menuItem,
	"selected-menu-item": selectedMenuItem,
	"close-button": closeButton,
	content,
	footer,
	help
}
